# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - release
cache: packages

r_github_packages: r-lib/pkgdown

apt_packages:
  - libmagick++-dev
  - libpoppler-cpp-dev

before_install:
  - R -e "tinytex::install_tinytex()"

deploy:
  provider: script
  script: Rscript -e 'pkgdown::build_favicon(); pkgdown::deploy_site_github()'
  skip_cleanup: true
