---
title: "styledTables in pdf_document"
author: "Gregor de Cillia"
date: "17 5 2019"
output: pdf_document
vignette: >
  %\VignetteIndexEntry{styledTables in pdf_document}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
pkgdown:
  as_is: true
  extension: pdf
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In order to use `styledTables` in rmarkdown pdf documents, the resulting object
can be printed in the chunk. 

```{r}
library(styledTables)
library(dplyr)
set.seed(42)

# Create the styled table
st1 <- iris[sample(seq_len(nrow(iris)), 10),] %>%
    styled_table(keep_header = TRUE)

# Apply several styling functions
st1 <- st1 %>%
    set_border_position("all", row_id = 1) %>%
    set_bold(row_id = 1) %>%
    set_fill_color("#00FF00", col_id = 5, condition = X == "setosa")
```



```{r cars}
st1
```

Another way is to directly embed some LaTeX code generated by `styledTables`. For this, the
function `embed_latex_rmd` can be used.

```{r}
embed_latex_rmd(st1)
```
